// @ts-check
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

const site = 'https://melhorparafusadeira.com.br';

const redirects = {
  '/melhor-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira' },
  '/melhor-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-furadeira' },
  '/melhor-parafusadeira-custo-beneficio': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira-custo-beneficio' },
  '/melhor-furadeira-e-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-furadeira-e-parafusadeira' },
  '/melhores-marcas-de-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/melhores-marcas-de-furadeira' },
  '/parafusadeira-black-tools-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-black-tools-e-boa/' },
  '/como-destravar-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-destravar-parafusadeira' },
  '/melhor-parafusadeira-dewalt': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira-dewalt' },
  '/qual-a-melhor-parafusadeira-12v-ou-20v': { status: 301, destination: 'https://mestredasferramentas.com.br/qual-a-melhor-parafusadeira-12v-ou-20v' },
  '/como-usar-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-usar-parafusadeira' },
  '/como-usar-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-usar-furadeira' },
  '/parafusadeira-wap-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-wap-e-boa' },
  '/como-escolher-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-escolher-parafusadeira' },
  '/qual-a-melhor-parafusadeira-bosch-ou-dewalt': { status: 301, destination: 'https://mestredasferramentas.com.br/qual-a-melhor-parafusadeira-bosch-ou-dewalt' },
  '/como-furar-madeira-com-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-furar-madeira-com-parafusadeira' },
  '/melhor-bits-para-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-bits-para-parafusadeira' },
  '/como-tirar-parafuso-espanado-com-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-tirar-parafuso-espanado-com-parafusadeira' },
  '/como-tirar-a-bateria-da-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-tirar-a-bateria-da-parafusadeira' },
  '/como-usar-furadeira-com-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-usar-furadeira-com-parafusadeira' },
  '/qual-a-diferenca-entre-parafusadeira-e-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/qual-a-diferenca-entre-parafusadeira-e-furadeira' },
  '/como-escolher-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-escolher-furadeira' },
  '/qual-o-melhor-torque-para-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/qual-o-melhor-torque-para-parafusadeira' },
  '/como-usar-furadeira-para-colocar-cortina': { status: 301, destination: 'https://mestredasferramentas.com.br/como-usar-furadeira-para-colocar-cortina' },
  '/como-furar-parede-com-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-furar-parede-com-furadeira' },
  '/como-furar-parede-de-concreto-with-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-furar-parede-de-concreto-com-furadeira' },
  '/como-usar-serra-copo-na-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-usar-serra-copo-na-furadeira' },
  '/como-saber-se-a-furadeira-e-110-ou-220': { status: 301, destination: 'https://mestredasferramentas.com.br/como-saber-se-a-furadeira-e-110-ou-220' },
  '/como-saber-se-a-parafusadeira-dewalt-e-original': { status: 301, destination: 'https://mestredasferramentas.com.br/como-saber-se-a-parafusadeira-dewalt-e-original' },
  '/melhor-parafusadeira-20v': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira-20v' },
  '/como-aumentar-a-potencia-da-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-aumentar-a-potencia-da-parafusadeira' },
  '/como-tirar-rebite-com-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-tirar-rebite-com-parafusadeira' },
  '/qual-melhor-compra-parafusadeira-a-bateria-ou-a-eletrica': { status: 301, destination: 'https://mestredasferramentas.com.br/qual-melhor-compra-parafusadeira-a-bateria-ou-a-eletrica' },
  '/furadeira-e-parafusadeira-wap-21v-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-e-parafusadeira-wap-21v-e-boa' },
  '/qual-melhor-mandril-para-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/qual-melhor-mandril-para-furadeira' },
  '/parafusadeira-vonder-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-vonder-e-boa' },
  '/parafusadeira-mondial-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-mondial-e-boa' },
  '/melhor-parafusadeira-bosch': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira-bosch' },
  '/melhor-furadeira-makita': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-furadeira-makita' },
  '/parafusadeira-nakasaki-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-nakasaki-e-boa' },
  '/parafusadeira-deko-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-deko-e-boa' },
  '/furadeira-e-parafusadeira-wesco-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-e-parafusadeira-wesco-e-boa' },
  '/furadeira-e-parafusadeira-dwt-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-e-parafusadeira-dwt-e-boa' },
  '/furadeira-tramontina-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-tramontina-e-boa' },
  '/parafusadeira-hammer-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-hammer-e-boa' },
  '/furadeira-e-parafusadeira-philco-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-e-parafusadeira-philco-e-boa' },
  '/parafusadeira-stanley-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-stanley-e-boa' },
  '/furadeira-skil-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-skil-e-boa' },
  '/melhor-broca-para-concreto': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-broca-para-concreto' },
  '/melhor-broca-para-madeira': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-broca-para-madeira' },
  '/melhor-broca-para-ferro': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-broca-para-ferro' },
  '/melhor-parafusadeira-12v': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira-12v' },
  '/melhor-jogo-de-brocas': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-jogo-de-brocas' },
  '/melhor-furadeira-bosch': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-furadeira-bosch' },
  '/furadeira-titanium-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-titanium-e-boa' },
  '/melhor-parafusadeira-de-impacto': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira-de-impacto' },
  '/parafusadeira-bosch-gsr-1000-smart-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-bosch-gsr-1000-smart-e-boa' },
  '/parafusadeira-bosch-gsr-7-14e-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-bosch-gsr-7-14e-e-boa' },
  '/parafusadeira-vonder-pfv-012-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/parafusadeira-vonder-pfv-012-e-boa' },
  '/furadeira-bosch-450w-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-bosch-450w-e-boa' },
  '/furadeira-bosch-550w-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-bosch-550w-e-boa' },
  '/furadeira-bleken-decker-560w-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-bleken-decker-560w-e-boa' },
  '/furadeira-makita-hp1640-e-boa': { status: 301, destination: 'https://mestredasferramentas.com.br/furadeira-makita-hp1640-e-boa' },
  '/como-saber-se-a-parafusadeira-esta-carregada': { status: 301, destination: 'https://mestredasferramentas.com.br/como-saber-se-a-parafusadeira-esta-carregada' },
  '/melhor-parafusadeira-brushless': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-parafusadeira-brushless' },
  '/o-que-e-uma-parafusadeira-brushless': { status: 301, destination: 'https://mestredasferramentas.com.br/o-que-e-uma-parafusadeira-brushless' },
  '/qual-a-diferenca-entre-chave-de-impacto-e-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/qual-a-diferenca-entre-chave-de-impacto-e-parafusadeira' },
  '/melhor-bateria-para-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/melhor-bateria-para-parafusadeira' },
  '/vale-a-pena-comprar-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/vale-a-pena-comprar-parafusadeira' },
  '/como-tirar-a-broca-da-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-tirar-a-broca-da-parafusadeira' },
  '/o-que-e-parafusadeira-de-impacto': { status: 301, destination: 'https://mestredasferramentas.com.br/o-que-e-parafusadeira-de-impacto' },
  '/o-que-e-bits-de-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/o-que-e-bits-de-parafusadeira' },
  '/para-que-serve-o-carvao-da-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/para-que-serve-o-carvao-da-furadeira' },
  '/o-que-significa-l-e-r-na-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/o-que-significa-l-e-r-na-furadeira' },
  '/como-trocar-o-carvao-da-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-trocar-o-carvao-da-furadeira' },
  '/o-que-e-funcao-percutor-na-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/o-que-e-funcao-percutor-na-parafusadeira' },
  '/tipos-de-parafusadeira-qual-a-ideal-para-cada-trabalho': { status: 301, destination: 'https://mestredasferramentas.com.br/tipos-de-parafusadeira-qual-a-ideal-para-cada-trabalho' },
  '/como-polir-carro-com-parafusadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-polir-carro-com-parafusadeira' },
  '/como-trocar-o-mandril-da-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-trocar-o-mandril-da-furadeira' },
  '/seguranca-com-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/seguranca-com-furadeira' },
  '/como-diminuir-o-barulho-da-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-diminuir-o-barulho-da-furadeira' },
  '/como-funciona-furadeira-de-impacto': { status: 301, destination: 'https://mestredasferramentas.com.br/como-funciona-furadeira-de-impacto' },
  '/como-furar-vidro-com-furadeira': { status: 301, destination: 'https://mestredasferramentas.com.br/como-furar-vidro-com-furadeira' },
} as const;

// https://astro.build/config
export default defineConfig({
  site,
  integrations: [
    react(),
    sitemap({
      customPages: Object.keys(redirects).map(path => `${site}${path}`)
    }),
  ],
  redirects
});